const H=window.PARTNER_HEADERS, R=window.PARTNER_ROWS.map(r=>Object.fromEntries(H.map((h,i)=>[h,r[i]||''])));
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const today=new Date();const currentMonth=today.getMonth()+1;
const $=id=>document.getElementById(id), uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
const roleRank=p=>/gerente/i.test(p)&&!/sub/i.test(p)?1:/sub/i.test(p)?2:/super/i.test(p)?3:/bar/i.test(p)?4:9;
const roleName=p=>/gerente/i.test(p)&&!/sub/i.test(p)?'Gerente':/sub/i.test(p)?'Subgerente':/super/i.test(p)?'Supervisor':/bar/i.test(p)?'Baristas':'Otros';
const dateParts=s=>{let d=new Date((s||'')+'T00:00:00');return isNaN(d)?null:{d,day:d.getDate(),month:d.getMonth()+1,year:d.getFullYear()}};
function fillSelect(el,items,all='Todas'){el.innerHTML=`<option value="">${all}</option>`+items.map(x=>`<option>${x}</option>`).join('')}
function init(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
  ['pRegion','aRegion','bRegion'].forEach(id=>fillSelect($(id),uniq(R.map(x=>x.region))));
  ['aMonth','bMonth'].forEach(id=>{$(id).innerHTML=months.map((m,i)=>`<option value="${i+1}" ${i+1==currentMonth?'selected':''}>${m}</option>`).join('')});
  ['pRegion','pDM','pStore','aRegion','aDM','aMonth','aSearch','bRegion','bDM','bMonth','bSearch'].forEach(id=>$(id).addEventListener('input',renderAll)); renderAll();
  if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');}
function filterBase(prefix){let region=$(prefix+'Region')?.value||'',dm=$(prefix+'DM')?.value||'',store=$(prefix+'Store')?.value||'';return R.filter(x=>(!region||x.region==region)&&(!dm||x.dm==dm)&&(!store||x.tienda==store))}
function cascade(prefix){let region=$(prefix+'Region').value, oldDM=$(prefix+'DM').value, oldStore=$(prefix+'Store')?$(prefix+'Store').value:'';let list=R.filter(x=>!region||x.region==region), dms=uniq(list.map(x=>x.dm));fillSelect($(prefix+'DM'),dms,'Todos');if(dms.includes(oldDM))$(prefix+'DM').value=oldDM;list=list.filter(x=>!$(prefix+'DM').value||x.dm==$(prefix+'DM').value);if($(prefix+'Store')){let stores=uniq(list.map(x=>x.tienda));fillSelect($(prefix+'Store'),stores,'Todas');if(stores.includes(oldStore))$(prefix+'Store').value=oldStore;}}
function renderPartner(){cascade('p');let data=filterBase('p');if(!data.length)data=R.slice(0,0);let stores=uniq(data.map(x=>x.tienda)),dms=uniq(data.map(x=>x.dm));$('kPartners').textContent=data.length;$('kStores').textContent=stores.length;$('kDMs').textContent=dms.length;$('storeTitle').textContent=$('pStore').value||'Resumen Partner';$('storeMeta').textContent=[$('pRegion').value||'Todas las regiones',$('pDM').value||'Todos los DM'].join(' · ');
  let f=data.filter(x=>x.sexo=='F').length,m=data.filter(x=>x.sexo=='M').length,pct=data.length?Math.round(f/data.length*100):0;$('donut').style.setProperty('--pct',pct);$('donutPct').textContent=pct+'%';$('womenPct').textContent=pct+'% Mujeres';$('menPct').textContent=(data.length?Math.round(m/data.length*100):0)+'% Hombres';
  const roles=['Gerente','Subgerente','Supervisor','Baristas'];let max=1;let counts={};roles.forEach(r=>counts[r]=data.filter(x=>roleName(x.puesto)==r).length);max=Math.max(1,...Object.values(counts));$('roleBars').innerHTML=roles.map(r=>`<div class="barRow"><b>${r}</b> <span>${counts[r]}</span><div><i style="width:${counts[r]/max*100}%"></i></div></div>`).join('');
  let grouped={};data.sort((a,b)=>roleRank(a.puesto)-roleRank(b.puesto)||a.nombre.localeCompare(b.nombre,'es')).forEach(x=>(grouped[roleName(x.puesto)]??=[]).push(x));$('hierarchy').innerHTML=roles.map(r=>{let arr=grouped[r]||[];return `<article class="role"><h2>${r}<span class="badge">${arr.length}</span></h2>${arr.map(personCard).join('')||'<small>Sin partners</small>'}</article>`}).join('');}
function personCard(x){return `<div class="person" onclick='showDetail(${JSON.stringify(x).replaceAll("'","&#39;")})'><div><b>${x.nombre}</b><small>${x.puesto} · ${x.tienda}</small></div><span class="badge">${x.turno}</span></div>`}
function yearsSince(s){let p=dateParts(s);if(!p)return 0;let y=today.getFullYear()-p.year;if(today.getMonth()+1<p.month||(today.getMonth()+1==p.month&&today.getDate()<p.day))y--;return Math.max(0,y)}
function renderCeleb(type){let pre=type=='a'?'a':'b';cascade(pre);let month=+$(pre+'Month').value,search=($(pre+'Search').value||'').toLowerCase();let data=filterBase(pre).filter(x=>{let p=dateParts(type=='a'?x.ingreso:x.nac);return p&&p.month==month&&(!search||(x.nombre+' '+x.tienda).toLowerCase().includes(search))}).sort((x,y)=>dateParts(type=='a'?x.ingreso:x.nac).day-dateParts(type=='a'?y.ingreso:y.nac).day||x.nombre.localeCompare(y.nombre,'es'));
  $(pre+'MonthTitle').textContent=months[month-1];$(pre+'Count').textContent=data.length+(type=='a'?' aniversarios':' cumpleaños');let html=data.slice(0,48).map(x=>{let p=dateParts(type=='a'?x.ingreso:x.nac), years=yearsSince(x.ingreso);return `<div class="celebration"><b>${String(p.day).padStart(2,'0')} · ${x.nombre}</b><small>${x.tienda} · ${x.dm}</small>${type=='a'?`<small>${years} años en la marca</small>`:''}</div>`}).join('')||'<div class="celebration"><b>Sin registros para este filtro</b><small>Ajusta Región, DM o Mes.</small></div>';$(pre+'List').innerHTML=html;}
function renderAll(){renderPartner();renderCeleb('a');renderCeleb('b')}
function showDetail(x){$('detailBody').innerHTML=`<h2>${x.nombre}</h2><p><b># Empleado:</b> ${x.num}</p><p><b>Puesto:</b> ${x.puesto}</p><p><b>Tienda:</b> ${x.tienda}</p><p><b>DM:</b> ${x.dm}</p><p><b>Región:</b> ${x.region}</p><p><b>Jornada:</b> ${x.turno}</p><p><b>Ingreso:</b> ${x.ingreso} · ${yearsSince(x.ingreso)} años</p>`;$('detail').showModal()}
init();
